import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

const IMPROMPTU=[
'Describe a decision that changed your direction.','What makes someone a great communicator?','Explain a complex idea to a 12-year-old.','What would you do with an unexpected free afternoon?','Tell a story about a time you had to adapt quickly.','Is failure necessary for success?','What is one skill everyone should learn before starting work?','Describe a place that changed how you think.','Should people follow their passion or pursue stability?','What makes a good leader?','Explain something you know well without using technical language.','What is a problem in your community you would like to solve?'
];
const RESEARCH=[
'How does a black hole form?','Why do people procrastinate?','How does mRNA work?','Why do we dream?','How does inflation affect everyday life?','What causes the seasons?','How does the internet find a website?','Why do humans form habits?','How does CRISPR work?','What makes a city walkable?','Why do languages change over time?','How does sleep affect memory?'
];

function App(){
 const[mode,setMode]=useState('impromptu'),[topic,setTopic]=useState(IMPROMPTU[0]),[prep,setPrep]=useState(30),[speak,setSpeak]=useState(60),[research,setResearch]=useState(5),[phase,setPhase]=useState('idle'),[left,setLeft]=useState(60),[rounds,setRounds]=useState(()=>+localStorage.ssRounds||0),[history,setHistory]=useState(()=>JSON.parse(localStorage.ssHistory||'[]')),[recording,setRecording]=useState(false),[audioUrl,setAudioUrl]=useState(''),[error,setError]=useState(''),media=useRef(),chunks=useRef([]);
 const currentTopics=mode==='impromptu'?IMPROMPTU:RESEARCH;
 function draw(){const t=currentTopics[Math.floor(Math.random()*currentTopics.length)];setTopic(t);setError('');setAudioUrl('');setPhase('idle');setLeft(mode==='impromptu'?speak:research*60)}
 function begin(){setError('');setAudioUrl('');if(mode==='impromptu'){setLeft(prep);setPhase('prep')}else{setLeft(research*60);setPhase('research')}}
 useEffect(()=>{if(!['prep','speak','research'].includes(phase))return;const id=setInterval(()=>setLeft(v=>{if(v<=1){clearInterval(id);if(phase==='prep'){setPhase('speak');setLeft(speak);startRecording()}else if(phase==='research'){setPhase('explain');setLeft(speak);startRecording()}else finish();return 0}return v-1}),1000);return()=>clearInterval(id)},[phase]);
 async function startRecording(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError('Recording is not supported in this browser. Try Chrome.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const type=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const r=new MediaRecorder(stream,{mimeType:type});chunks.current=[];r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type});setAudioUrl(URL.createObjectURL(blob));setRecording(false)};r.start();media.current=r;setRecording(true)}catch{setError('Microphone access was blocked. Allow microphone access and try again.')}}
 function stopRecording(){if(media.current&&media.current.state!=='inactive')media.current.stop()}
 function finish(){stopRecording();setPhase('done');setRounds(n=>{const x=n+1;localStorage.ssRounds=x;return x});const item={q:topic,mode,date:new Date().toISOString()};const next=[item,...history].slice(0,20);setHistory(next);localStorage.ssHistory=JSON.stringify(next)}
 function reset(){setPhase('idle');setAudioUrl('');setError('');setLeft(mode==='impromptu'?speak:research*60)}
 function switchMode(m){setMode(m);const list=m==='impromptu'?IMPROMPTU:RESEARCH;const t=list[Math.floor(Math.random()*list.length)];setTopic(t);setPhase('idle');setAudioUrl('');setLeft(m==='impromptu'?speak:research*60)}
 const mins=Math.floor(left/60),secs=String(left%60).padStart(2,'0');
 return <div className="app"><header><div className="brand">STOP<span>SCROLLING</span></div><nav><button className={mode==='impromptu'?'active':''}onClick={()=>switchMode('impromptu')}>Impromptu</button><button className={mode==='research'?'active':''}onClick={()=>switchMode('research')}>Deep Research</button><button className="progressLink"onClick={()=>document.getElementById('progress')?.scrollIntoView({behavior:'smooth'})}>Progress</button></nav><button className="pro">PRO · COMING SOON</button></header>
 <main><section className="hero"><label>PUT THE PHONE DOWN. PICK A TOPIC.</label><h1>Think. Speak.<br/><i>Get better.</i></h1><p>A simple practice space for thinking clearly when you don't have time to prepare.</p></section>
 <div className="modeSwitch"><button className={mode==='impromptu'?'selected':''}onClick={()=>switchMode('impromptu')}><span>🎙️</span><b>Impromptu</b><small>Think fast. Speak clearly.</small></button><button className={mode==='research'?'selected':''}onClick={()=>switchMode('research')}><span>🧠</span><b>Deep Research</b><small>Learn. Close the notes. Explain.</small></button></div>
 <section className="card"><div className="top"><span>{mode==='impromptu'?'IMPROMPTU':'DEEP RESEARCH'}</span><small>{rounds} rounds completed</small></div><div className="topicLabel">{mode==='impromptu'?'YOUR TOPIC':'RESEARCH THIS'}</div><h2>{topic}</h2>
 {phase==='idle'&&<div className="settings">{mode==='impromptu'?<><label>PREP TIME<select value={prep}onChange={e=>setPrep(+e.target.value)}><option value="15">15 seconds</option><option value="30">30 seconds</option><option value="60">1 minute</option><option value="120">2 minutes</option><option value="300">5 minutes</option></select></label><label>SPEAKING TIME<select value={speak}onChange={e=>setSpeak(+e.target.value)}><option value="60">1 minute</option><option value="120">2 minutes</option><option value="300">5 minutes</option><option value="600">10 minutes</option></select></label></>:<><label>RESEARCH TIME<select value={research}onChange={e=>setResearch(+e.target.value)}><option value="2">2 minutes</option><option value="5">5 minutes</option><option value="10">10 minutes</option><option value="15">15 minutes</option></select></label><label>EXPLAINING TIME<select value={speak}onChange={e=>setSpeak(+e.target.value)}><option value="60">1 minute</option><option value="120">2 minutes</option><option value="300">5 minutes</option><option value="600">10 minutes</option></select></label></>}
 </div>}
 {phase!=='idle'&&phase!=='done'&&<div className="phaseTag">{phase==='prep'?'GET READY':phase==='research'?'RESEARCH':'SPEAK'}</div>}
 {phase!=='done'&&<div className="timer">{mins>0?<>{mins}<em>m</em> </>:null}{secs}<em>s</em></div>}
 <div className="actions">{phase==='idle'?<><button className="primary"onClick={begin}>{mode==='impromptu'?'Start →':'Start research →'}</button><button className="ghost"onClick={draw}>Draw another</button></>:phase==='done'?<><button className="primary"onClick={reset}>Try again →</button><button className="ghost"onClick={draw}>New topic</button></>:<button className="finish"onClick={finish}>{phase==='research'?'Finish research & explain':'Finish response'}</button>}</div>
 <div className="live">{phase==='prep'?'Prepare your answer. No notes needed.':phase==='research'?'Research in another tab. Your timer keeps running.':phase==='speak'?'Recording — speak naturally.':phase==='explain'?'Now explain it in your own words.':'No feed. No scrolling. Just one topic.'}</div>{recording&&<div className="recordDot">● Recording</div>}{error&&<div className="error">{error}</div>}
 {phase==='done'&&<div className="done"><b>Round complete.</b><p>You showed up. That's the rep.</p>{audioUrl&&<audio controls src={audioUrl}/>}<small>Your recording stays in this browser session.</small></div>}
 </section>
 <div className="steps"><div><b>01</b>Draw <span>a topic</span></div><div><b>02</b>Think <span>on your own</span></div><div><b>03</b>Speak <span>without notes</span></div><div><b>04</b>Repeat <span>get sharper</span></div></div>
 <section id="progress" className="progress"><label>YOUR PRACTICE</label><h2>Small reps.<br/><i>Real progress.</i></h2><div className="stats"><div><b>{rounds}</b><span>Rounds</span></div><div><b>{history.length}</b><span>Topics tried</span></div><div><b>{new Set(history.map(x=>x.q)).size}</b><span>Unique topics</span></div></div></section>
 </main><footer>STOP SCROLLING <span>Think. Speak. Get better.</span></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);